// @ts-check
const { test, expect } = require("@playwright/test");

// Welcome to Argos Playwright example

// This spec file is generated by Playwright during installation.

// We have added the Playwright command to take a screenshot. The path param
// specify where to save the image.

// We store the screenshot to the "screenshots" folder. The folder will be
// upload to Argos by the CI.

// We have added the `browserName` to the `path` to avoid override when
// puppeteer launch the test on multiple browsers.

const screenshotsFolder = "screenshots";

test("homepage has Playwright in title and get started link linking to the intro page", async ({
  page,
  browserName,
}) => {
  await page.goto("https://playwright.dev/");

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // create a locator
  const getStarted = page.locator("text=Get Started");

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute("href", "/docs/intro");

  // Click the get started link.
  await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);

  // 👇 That's how we take screenshot with playwright
  await page.screenshot({
    path: `${screenshotsFolder}/${browserName}-screenshot.png`,
  });
});
