export type ToolbarState = {
  isBold: boolean;
  canBold: boolean;
  isItalic: boolean;
  canItalic: boolean;
  isStrike: boolean;
  canStrike: boolean;
  isUnderline: boolean;
  canUnderline: boolean;
  isCode: boolean;
  canCode: boolean;
  isCodeBlock: boolean;
  canCodeBlock: boolean;
  isBlockquote: boolean;
  canBlockquote: boolean;
  isLink: boolean;
  linkHref: string | null;
  canSetLink: boolean;
  isBulletList: boolean;
  isOrderedList: boolean;
  headingLevel: number | null;
  selectionFrom: number;
  selectionTo: number;
  selectionEmpty: boolean;
};
