packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@eslint/js": ^9.33.0
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7
  "@types/express": ^5.0.3
  "@types/express-serve-static-core": ^5.0.7
  express: ^5.1.0
  react: ^19.1.1
  react-dom: ^19.1.1
  undici: ^7.13.0
# Wait at least 1 day before installing new packages
# To ensure packages are not compromised
minimumReleaseAge: 1440
