packages:
  - apps/*
  - packages/*

catalog:
  '@types/express': ^5.0.6
  '@types/express-serve-static-core': ^5.0.7
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  eslint: ^10.0.1
  express: ^5.2.1
  lodash: ^4.17.23
  lodash-es: ^4.17.23
  react: ^19.2.4
  react-dom: ^19.2.4
  undici: ^7.22.0
  zod: ^4.3.6
