name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies and launch Cypress tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build
          start: pnpm run start

      - name: Argos screenshots upload
        if: ${{ always() }}
        run: pnpm exec argos upload cypress/screenshots
