name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install dependencies and launch Cypress tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start

      - name: Argos screenshots upload
        if: ${{ always() }}
        run: npx @argos-ci/cli upload cypress/screenshots
