/**
 * Extracts the `monaco-editor` version resolved in `pnpm-lock.yaml` and writes
 * it to `src/web/monaco-version.generated.ts` so it can be consumed at runtime
 * to build a Content-Security-Policy that only allows the exact Monaco editor
 * version loaded from the jsDelivr CDN by `@monaco-editor/react`.
 *
 * Run it with `pnpm run generate-monaco-version`. It is also run as part of the
 * `build` script.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { parse as parseYaml } from "yaml";

/** Workspace importer (relative to the repository root) that uses Monaco. */
const FRONTEND_IMPORTER = "apps/frontend";

/** Package that pulls in (and loads) `monaco-editor`. */
const MONACO_REACT_PACKAGE = "@monaco-editor/react";

/** jsDelivr CDN base from which `@monaco-editor/loader` loads Monaco. */
const MONACO_CDN_BASE = "https://cdn.jsdelivr.net/npm/monaco-editor";

interface PnpmImporterDependency {
  specifier: string;
  version: string;
}

interface PnpmImporter {
  dependencies?: Record<string, PnpmImporterDependency>;
  devDependencies?: Record<string, PnpmImporterDependency>;
}

interface PnpmLockfile {
  importers?: Record<string, PnpmImporter>;
}

/**
 * Extracts the `monaco-editor` version used by the frontend from the content of
 * a `pnpm-lock.yaml` file.
 *
 * The version is read from the peer dependency encoded in the resolved
 * `@monaco-editor/react` entry (e.g. `4.7.0(monaco-editor@0.55.1)(...)`), which
 * is exactly the version `@monaco-editor/react` loads from the CDN.
 */
export function parseMonacoVersionFromLock(lockContent: string): string {
  const lockfile = parseYaml(lockContent) as PnpmLockfile;

  const importer = lockfile.importers?.[FRONTEND_IMPORTER];
  if (!importer) {
    throw new Error(
      `Could not find importer "${FRONTEND_IMPORTER}" in pnpm-lock.yaml.`,
    );
  }

  const entry =
    importer.dependencies?.[MONACO_REACT_PACKAGE] ??
    importer.devDependencies?.[MONACO_REACT_PACKAGE];
  if (!entry) {
    throw new Error(
      `Could not find "${MONACO_REACT_PACKAGE}" in the "${FRONTEND_IMPORTER}" dependencies of pnpm-lock.yaml.`,
    );
  }

  const match = entry.version.match(/monaco-editor@([^()]+)/);
  if (!match?.[1]) {
    throw new Error(
      `Could not extract the monaco-editor version from "${entry.version}".`,
    );
  }

  return match[1];
}

/** Builds the jsDelivr CDN URL for a given Monaco editor version. */
export function getMonacoCdnUrl(version: string): string {
  return `${MONACO_CDN_BASE}@${version}/`;
}

/** Generates the content of the `monaco-version.generated.ts` module. */
export function generateMonacoVersionModule(version: string): string {
  const cdnUrl = getMonacoCdnUrl(version);
  return `// This file is auto-generated by scripts/extract-monaco-version.ts.
// Do not edit it manually. Run \`pnpm run generate-monaco-version\` to update it.

/**
 * Version of \`monaco-editor\` resolved in pnpm-lock.yaml and loaded from the
 * jsDelivr CDN by \`@monaco-editor/react\`.
 */
export const MONACO_EDITOR_VERSION = ${JSON.stringify(version)};

/**
 * jsDelivr CDN URL for the pinned Monaco editor version. Used to restrict the
 * Content-Security-Policy \`script-src\` directive to this exact version.
 */
export const MONACO_EDITOR_CDN_URL =
  ${JSON.stringify(cdnUrl)};
`;
}

const LOCKFILE_PATH = path.resolve(
  import.meta.dirname,
  "../../../pnpm-lock.yaml",
);

const OUTPUT_PATH = path.resolve(
  import.meta.dirname,
  "../src/web/monaco-version.generated.ts",
);

export function run(): void {
  const lockContent = readFileSync(LOCKFILE_PATH, "utf8");
  const version = parseMonacoVersionFromLock(lockContent);
  writeFileSync(OUTPUT_PATH, generateMonacoVersionModule(version), "utf8");
  console.log(
    `Monaco editor version ${version} written to ${path.relative(process.cwd(), OUTPUT_PATH)}`,
  );
}

// Only run when executed directly (not when imported by tests).
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  run();
}
