/// <reference types="cypress" />

// Welcome to Cypress + Argos!

// This spec file is an extract of the first example generated by Cypress.
//
// We have added the `cy.argosSnapshot` command
// introduced by @argos/cypress package to take screenshots.

describe("example to-do app", () => {
  beforeEach(() => {
    cy.visit("https://example.cypress.io/todo");
  });

  it("displays two todo items by default", () => {
    cy.get(".todo-list li").should("have.length", 2);
    cy.get(".todo-list li").first().should("have.text", "Pay electric bill");
    cy.get(".todo-list li").last().should("have.text", "Walk the dog");

    // 👇 That's how we take screenshot
    cy.argosScreenshot("with two items");
  });

  it("can add new todo items", () => {
    const newItem = "Feed the cat";
    cy.get("[data-test=new-todo]").type(`${newItem}{enter}`);
    cy.get(".todo-list li")
      .should("have.length", 3)
      .last()
      .should("have.text", newItem);

    //👇 Here, an other screenshot will be taken
    cy.argosScreenshot("with an added item");
  });
});
