interface Account implements Node {
  additionalScreenshotsCost: Float!
  avatar: AccountAvatar!
  blockWhenSpendLimitIsReached: Boolean!
  consumptionRatio: Float!
  currentPeriodScreenshots: Int!
  githubAccount: GithubAccount
  gitlabAccessToken: String
  gitlabBaseUrl: String
  glNamespaces: GlApiNamespaceConnection
  hasForcedPlan: Boolean!
  id: ID!
  includedScreenshots: Int!
  meteredSpendLimitByPeriod: Int
  metrics(input: AccountMetricsInput!): AccountMetrics!
  name: String
  periodEndDate: DateTime
  periodStartDate: DateTime
  permissions: [AccountPermission!]!
  plan: Plan
  projects(after: Int = 0, first: Int = 30): ProjectConnection!
  slackInstallation: SlackInstallation
  slug: String!
  stripeClientReferenceId: String!
  stripeCustomerId: String
  subscription: AccountSubscription
  subscriptionStatus: AccountSubscriptionStatus
}

type AccountAvatar {
  color: String!
  initial: String!
  url(size: Int!): String
}

type AccountBuildsMetrics {
  all: AccountMetricData!
  projects: [Project!]!
  series: [AccountMetricDataPoint!]!
}

type AccountMetricData {
  projects: JSONObject!
  total: Int!
}

type AccountMetricDataPoint {
  projects: JSONObject!
  total: Int!
  ts: Timestamp!
}

type AccountMetrics {
  builds: AccountBuildsMetrics!
  screenshots: AccountScreenshotMetrics!
}

input AccountMetricsInput {
  from: DateTime!
  groupBy: TimeSeriesGroupBy!
  projectIds: [ID!]
}

enum AccountPermission {
  admin
  view
}

type AccountScreenshotMetrics {
  all: AccountMetricData!
  projects: [Project!]!
  series: [AccountMetricDataPoint!]!
}

type AccountSubscription implements Node {
  currency: Currency!
  endDate: DateTime
  id: ID!
  paymentMethodFilled: Boolean!
  provider: AccountSubscriptionProvider!
  status: AccountSubscriptionStatus!
  trialDaysRemaining: Int
}

enum AccountSubscriptionProvider {
  github
  stripe
}

enum AccountSubscriptionStatus {
  """Ongoing paid subscription"""
  active

  """Post-cancelation date"""
  canceled

  """Incomplete"""
  incomplete

  """Incomplete expired"""
  incomplete_expired

  """Payment due"""
  past_due

  """Paused"""
  paused

  """Trial expired"""
  trial_expired

  """Ongoing trial"""
  trialing

  """Unpaid"""
  unpaid
}

input AddContributorToProjectInput {
  level: ProjectUserLevel!
  projectId: ID!
  userAccountId: ID!
}

type AutomationAction {
  action: String!
  actionPayload: JSONObject!
}

input AutomationActionInput {
  payload: JSONObject!
  type: String!
}

type AutomationActionSendSlackMessagePayload {
  channelId: String!
  name: String!
  slackId: String!
}

type AutomationCondition {
  type: String!
  value: String!
}

input AutomationConditionInput {
  type: String!
  value: String!
}

type AutomationConditions {
  all: [AutomationCondition!]!
}

type AutomationRule implements Node {
  active: Boolean!
  createdAt: DateTime!
  id: ID!
  if: AutomationConditions!
  lastAutomationRunDate: DateTime
  name: String!
  on: [String!]!
  then: [AutomationAction!]!
  updatedAt: DateTime!
}

type AutomationRuleConnection implements Connection {
  edges: [AutomationRule!]!
  pageInfo: PageInfo!
}

type AutomationRun implements Node {
  buildId: String
  createdAt: DateTime!
  event: String!
  id: ID!
  updatedAt: DateTime!
}

enum BaseBranchResolution {
  """Base branch is resolved from the project settings"""
  project

  """Base branch is resolved from the pull request"""
  pullRequest

  """Base branch specified by the user through the API / SDK"""
  user
}

type Build implements Node {
  """Base branch used to resolve the base build"""
  baseBranch: String

  """Base branch resolved from"""
  baseBranchResolvedFrom: BaseBranchResolution

  """The base build that contains the base screenshot bucket"""
  baseBuild: Build

  """The screenshot bucket that serves as base for comparison"""
  baseScreenshotBucket: ScreenshotBucket

  """Branch"""
  branch: String

  """Commit"""
  commit: String!
  createdAt: DateTime!
  id: ID!

  """Aggregated metadata"""
  metadata: BuildMetadata

  """Mode"""
  mode: BuildMode!

  """Build name"""
  name: String!

  """Continuous number. It is incremented after each build"""
  number: Int!

  """Parallel infos"""
  parallel: BuildParallel

  """Pull request head commit"""
  prHeadCommit: String

  """Pull request number"""
  prNumber: Int

  """Pull request"""
  pullRequest: PullRequest

  """Effective build reviews"""
  reviews: [BuildReview!]!

  """
  The screenshot diffs between the base screenshot bucket of the compare screenshot bucket
  """
  screenshotDiffs(after: Int!, first: Int!): ScreenshotDiffConnection!

  """Build stats"""
  stats: BuildStats

  """Review status, conclusion or job status"""
  status: BuildStatus!

  """Build type"""
  type: BuildType
  updatedAt: DateTime!
}

type BuildConnection implements Connection {
  edges: [Build!]!
  pageInfo: PageInfo!
}

type BuildMetadata {
  testReport: TestReport
}

enum BuildMode {
  """Build is compared with a baseline found by analyzing Git history"""
  ci

  """Build is compared with the latest approved build"""
  monitoring
}

type BuildParallel {
  nonce: String!
  received: Int!
  total: Int!
}

type BuildReview implements Node {
  date: DateTime!
  id: ID!
  state: BuildReviewState!
  user: User
}

enum BuildReviewState {
  APPROVED
  PENDING
  REJECTED
}

type BuildStats {
  added: Int!
  changed: Int!
  failure: Int!
  removed: Int!
  retryFailure: Int!
  total: Int!
  unchanged: Int!
}

enum BuildStatus {
  """job status: aborted"""
  ABORTED

  """reviewStatus: accepted"""
  ACCEPTED

  """conclusion: changes-detected"""
  CHANGES_DETECTED

  """job status: complete"""
  ERROR

  """job status: expired"""
  EXPIRED

  """conclusion: no-changes"""
  NO_CHANGES

  """job status: pending"""
  PENDING

  """job status: progress"""
  PROGRESS

  """reviewStatus: rejected"""
  REJECTED
}

enum BuildType {
  """Comparison build"""
  check

  """No baseline build found"""
  orphan

  """Build auto-approved"""
  reference
}

input BuildsFilterInput {
  name: String
  status: [BuildStatus!]
  type: [BuildType!]
}

interface Connection {
  edges: [Node!]!
  pageInfo: PageInfo!
}

input CreateAutomationRuleInput {
  actions: [AutomationActionInput!]!
  conditions: [AutomationConditionInput!]!
  events: [String!]!
  name: String!
  projectId: String!
}

input CreateTeamInput {
  name: String!
}

type CreateTeamResult {
  redirectUrl: String!
  team: Team!
}

enum Currency {
  EUR
  USD
}

scalar Date

scalar DateTime

input DeleteTeamInput {
  accountId: ID!
}

input DisableGitHubSSOOnTeamInput {
  teamAccountId: ID!
}

input DisconnectGitHubAuthInput {
  accountId: ID!
}

input DisconnectGitLabAuthInput {
  accountId: ID!
}

input DisconnectGoogleAuthInput {
  accountId: ID!
}

input EnableGitHubSSOOnTeamInput {
  ghInstallationId: Int!
  teamAccountId: ID!
}

type GhApiInstallation implements Node {
  account: GhApiInstallationAccount!
  id: ID!
}

type GhApiInstallationAccount implements Node {
  id: ID!
  login: String!
  name: String
  url: String!
}

type GhApiInstallationConnection implements Connection {
  edges: [GhApiInstallation!]!
  pageInfo: PageInfo!
}

type GhApiRepository implements Node {
  id: ID!
  name: String!
  owner_login: String!
  updated_at: String!
}

type GhApiRepositoryConnection implements Connection {
  edges: [GhApiRepository!]!
  pageInfo: PageInfo!
}

enum GitHubAppType {
  light
  main
}

type GithubAccount implements Node {
  avatar: AccountAvatar!
  id: ID!
  lastLoggedAt: DateTime
  login: String!
  name: String
  url: String!
}

type GithubInstallation implements Node {
  ghAccount: GhApiInstallationAccount
  ghInstallation: GhApiInstallation
  id: ID!
}

type GithubPullRequest implements Node & PullRequest {
  closedAt: DateTime
  creator: GithubAccount
  date: DateTime
  draft: Boolean
  id: ID!
  merged: Boolean
  mergedAt: DateTime
  number: Int!
  state: PullRequestState
  title: String
  url: String!
}

type GithubRepository implements Node & Repository {
  defaultBranch: String!
  fullName: String!
  id: ID!
  private: Boolean!
  url: String!
}

type GitlabProject implements Node & Repository {
  defaultBranch: String!
  fullName: String!
  id: ID!
  private: Boolean!
  url: String!
}

type GitlabUser implements Node {
  id: ID!
  lastLoggedAt: DateTime
  name: String!
  url: String!
  username: String!
}

type GlApiNamespace implements Node {
  id: ID!
  isProjectToken: Boolean!
  kind: String!
  name: String!
  path: String!
}

type GlApiNamespaceConnection implements Connection {
  edges: [GlApiNamespace!]!
  pageInfo: PageInfo!
}

type GlApiProject implements Node {
  id: ID!
  last_activity_at: String!
  name: String!
  namespace: GlApiNamespace!
}

type GlApiProjectConnection implements Connection {
  edges: [GlApiProject!]!
  pageInfo: PageInfo!
}

type GoogleUser implements Node {
  id: ID!
  lastLoggedAt: DateTime
  name: String
  primaryEmail: String
}

input ImportGithubProjectInput {
  accountSlug: String!
  installationId: String!
  owner: String!
  repo: String!
}

input ImportGitlabProjectInput {
  accountSlug: String!
  gitlabProjectId: ID!
}

scalar JSONObject

enum JobStatus {
  aborted
  complete
  error
  pending
  progress
}

input LeaveTeamInput {
  teamAccountId: ID!
}

input LinkGithubRepositoryInput {
  installationId: String!
  owner: String!
  projectId: ID!
  repo: String!
}

input LinkGitlabProjectInput {
  gitlabProjectId: ID!
  projectId: ID!
}

enum MetricsPeriod {
  LAST_3_DAYS
  LAST_7_DAYS
  LAST_24_HOURS
  LAST_30_DAYS
  LAST_90_DAYS
}

type Mutation {
  """Accept an invitation to join a team"""
  acceptInvitation(token: String!): Team!

  """Add contributor to project"""
  addOrUpdateProjectContributor(input: AddContributorToProjectInput!): ProjectContributor!

  """Create automation"""
  createAutomationRule(input: CreateAutomationRuleInput!): AutomationRule!

  """Create a team"""
  createTeam(input: CreateTeamInput!): CreateTeamResult!

  """Deactivate automation"""
  deactivateAutomationRule(id: String!): AutomationRule!

  """Delete Project"""
  deleteProject(id: ID!): Boolean!

  """Delete team and all its projects"""
  deleteTeam(input: DeleteTeamInput!): Boolean!

  """Disable GitHub SSO"""
  disableGitHubSSOOnTeam(input: DisableGitHubSSOOnTeamInput!): Team!

  """Disconnect GitHub Account"""
  disconnectGitHubAuth(input: DisconnectGitHubAuthInput!): Account!

  """Disconnect GitLab Account"""
  disconnectGitLabAuth(input: DisconnectGitLabAuthInput!): Account!

  """Disconnect Google Account"""
  disconnectGoogleAuth(input: DisconnectGoogleAuthInput!): Account!

  """Enable GitHub SSO"""
  enableGitHubSSOOnTeam(input: EnableGitHubSSOOnTeamInput!): Team!

  """Import a project from GitHub"""
  importGithubProject(input: ImportGithubProjectInput!): Project!

  """Import a project from GitLab"""
  importGitlabProject(input: ImportGitlabProjectInput!): Project!

  """Leave a team"""
  leaveTeam(input: LeaveTeamInput!): Boolean!

  """Link GitHub Repository"""
  linkGithubRepository(input: LinkGithubRepositoryInput!): Project!

  """Link Gitlab Project"""
  linkGitlabProject(input: LinkGitlabProjectInput!): Project!
  ping: Boolean!

  """Regenerate project token"""
  regenerateProjectToken(id: ID!): Project!
  removeContributorFromProject(input: RemoveContributorFromProjectInput!): RemoveContributorFromProjectPayload!

  """Remove a user from a team"""
  removeUserFromTeam(input: RemoveUserFromTeamInput!): RemoveUserFromTeamPayload!

  """Set team default user level"""
  setTeamDefaultUserLevel(input: SetTeamDefaultUserLevelInput!): Team!

  """Set member level"""
  setTeamMemberLevel(input: SetTeamMemberLevelInput!): TeamMember!

  """Change the validationStatus on a build"""
  setValidationStatus(buildId: ID!, validationStatus: ValidationStatus!): Build!

  """Test automation rule by sending a test event"""
  testAutomation(input: TestAutomationRuleInput!): Boolean!

  """Transfer Project to another account"""
  transferProject(input: TransferProjectInput!): Project!

  """Uninstall Slack"""
  uninstallSlack(input: UninstallSlackInput!): Account!

  """Unlink GitHub Repository"""
  unlinkGithubRepository(input: UnlinkGithubRepositoryInput!): Project!

  """Unlink Gitlab Project"""
  unlinkGitlabProject(input: UnlinkGitlabProjectInput!): Project!

  """Update Account"""
  updateAccount(input: UpdateAccountInput!): Account!

  """Update automation"""
  updateAutomationRule(input: UpdateAutomationRuleInput!): AutomationRule!

  """Update Project"""
  updateProject(input: UpdateProjectInput!): Project!

  """Set project pull request comment"""
  updateProjectPrComment(input: UpdateProjectPrCommentInput!): Project!
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  totalCount: Int!
}

type Plan implements Node {
  displayName: String!
  fineGrainedAccessControlIncluded: Boolean!
  githubSsoIncluded: Boolean!
  id: ID!
  usageBased: Boolean!
}

type Project implements Node {
  """Owner of the project"""
  account: Account!

  """Glob pattern for auto-approved branches"""
  autoApprovedBranchGlob: String!

  """Automation rules"""
  automationRules(after: Int = 0, first: Int = 30): AutomationRuleConnection!

  """A single build linked to the project"""
  build(number: Int!): Build

  """Build names"""
  buildNames: [String!]!

  """Builds associated to the project"""
  builds(after: Int = 0, filters: BuildsFilterInput, first: Int = 30): BuildConnection!

  """Contributors"""
  contributors(after: Int = 0, first: Int = 30): ProjectContributorConnection!

  """Current month used screenshots"""
  currentPeriodScreenshots: Int!

  """Glob pattern for auto-approved branches edited by the user"""
  customAutoApprovedBranchGlob: String

  """Default base branch edited by the user"""
  customDefaultBaseBranch: String

  """Default base branch"""
  defaultBaseBranch: String!

  """Default user access level applied to members that are not contributors"""
  defaultUserLevel: ProjectUserLevel
  id: ID!

  """Latest auto-approved build"""
  latestAutoApprovedBuild: Build

  """Latest build"""
  latestBuild: Build
  name: String!

  """Determine permissions of the current user"""
  permissions: [ProjectPermission!]!

  """Pull request comment enabled"""
  prCommentEnabled: Boolean!

  """Override repository's Github privacy"""
  private: Boolean

  """Check if the project is public or not"""
  public: Boolean!

  """Repository associated to the project"""
  repository: Repository

  """Project slug"""
  slug: String!

  """Summary check"""
  summaryCheck: SummaryCheck!

  """Test associated to the project"""
  test(id: ID!): Test
  token: String

  """Total screenshots used"""
  totalScreenshots: Int!
}

type ProjectConnection implements Connection {
  edges: [Project!]!
  pageInfo: PageInfo!
}

type ProjectContributor implements Node {
  id: ID!
  level: ProjectUserLevel!
  project: Project!
  user: User!
}

type ProjectContributorConnection implements Connection {
  edges: [ProjectContributor!]!
  pageInfo: PageInfo!
}

enum ProjectPermission {
  admin
  review
  view
  view_settings
}

enum ProjectUserLevel {
  admin
  reviewer
  viewer
}

interface PullRequest implements Node {
  closedAt: DateTime
  date: DateTime
  draft: Boolean
  id: ID!
  merged: Boolean
  mergedAt: DateTime
  number: Int!
  state: PullRequestState
  title: String
  url: String!
}

enum PullRequestState {
  CLOSED
  OPEN
}

type Query {
  """Get Account by slug"""
  account(slug: String!): Account

  """Get Account by id"""
  accountById(id: ID!): Account

  """Get automation rule by ID"""
  automationRule(id: String!): AutomationRule
  ghApiInstallationRepositories(fromAuthUser: Boolean!, installationId: ID!, page: Int!, reposPerPage: Int): GhApiRepositoryConnection!
  glApiProjects(accountId: ID!, allProjects: Boolean!, groupId: ID, page: Int!, search: String, userId: ID): GlApiProjectConnection!
  invitation(token: String!): Team

  """Get the authenticated user"""
  me: User
  ping: Boolean!

  """Get a project"""
  project(accountSlug: String!, projectName: String!): Project

  """Get a project"""
  projectById(id: ID!): Project

  """Get Team by id"""
  teamById(id: ID!): Team
}

input RemoveContributorFromProjectInput {
  projectId: ID!
  userAccountId: ID!
}

type RemoveContributorFromProjectPayload {
  projectContributorId: ID!
}

input RemoveUserFromTeamInput {
  teamAccountId: ID!
  userAccountId: ID!
}

type RemoveUserFromTeamPayload {
  teamMemberId: ID!
}

interface Repository implements Node {
  defaultBranch: String!
  fullName: String!
  id: ID!
  private: Boolean!
  url: String!
}

type Screenshot implements Node {
  height: Int
  id: ID!
  metadata: ScreenshotMetadata
  originalUrl: String!
  playwrightTraceUrl: String
  url: String!
  width: Int
}

type ScreenshotBucket implements Node {
  branch: String
  commit: String!
  createdAt: DateTime!
  id: ID!
}

type ScreenshotDiff implements Node {
  baseScreenshot: Screenshot
  build: Build!

  """Change ID of the screenshot diff. Used to be indefied in a test."""
  changeId: String
  compareScreenshot: Screenshot
  createdAt: DateTime!
  group: String
  height: Int
  id: ID!
  last7daysOccurences: Int!

  """Name of the diff (either base or compare screenshot name)"""
  name: String!
  status: ScreenshotDiffStatus!
  test: Test
  threshold: Float
  url: String

  """
  Unique key to identify screenshot variant (browser, resolution, retries)
  """
  variantKey: String!
  width: Int
}

type ScreenshotDiffConnection implements Connection {
  edges: [ScreenshotDiff!]!
  pageInfo: PageInfo!
}

enum ScreenshotDiffStatus {
  added
  changed
  failure
  pending
  removed
  retryFailure
  unchanged
}

type ScreenshotMetadata {
  automationLibrary: ScreenshotMetadataAutomationLibrary!
  browser: ScreenshotMetadataBrowser
  colorScheme: ScreenshotMetadataColorScheme
  mediaType: ScreenshotMetadataMediaType
  previewUrl: String
  sdk: ScreenshotMetadataSDK!
  test: ScreenshotMetadataTest
  url: String
  viewport: ScreenshotMetadataViewport
}

type ScreenshotMetadataAutomationLibrary {
  name: String!
  version: String!
}

type ScreenshotMetadataBrowser {
  name: String!
  version: String!
}

enum ScreenshotMetadataColorScheme {
  dark
  light
}

type ScreenshotMetadataLocation {
  column: Int!
  file: String!
  line: Int!
}

enum ScreenshotMetadataMediaType {
  print
  screen
}

type ScreenshotMetadataSDK {
  name: String!
  version: String!
}

type ScreenshotMetadataTest {
  id: String
  location: ScreenshotMetadataLocation
  repeat: Int
  retries: Int
  retry: Int
  title: String!
  titlePath: [String!]!
}

type ScreenshotMetadataViewport {
  height: Int!
  width: Int!
}

input SetTeamDefaultUserLevelInput {
  level: TeamDefaultUserLevel!
  teamAccountId: ID!
}

input SetTeamMemberLevelInput {
  level: TeamUserLevel!
  teamAccountId: ID!
  userAccountId: ID!
}

type SlackInstallation implements Node {
  createdAt: DateTime!
  id: ID!
  teamDomain: String!
  teamName: String!
}

enum SummaryCheck {
  always
  auto
  never
}

type Team implements Account & Node {
  additionalScreenshotsCost: Float!
  avatar: AccountAvatar!
  blockWhenSpendLimitIsReached: Boolean!
  consumptionRatio: Float!
  currentPeriodScreenshots: Int!
  defaultUserLevel: TeamDefaultUserLevel!
  githubAccount: GithubAccount
  githubLightInstallation: GithubInstallation
  githubMembers(after: Int = 0, first: Int = 30, isTeamMember: Boolean): TeamGithubMemberConnection
  gitlabAccessToken: String
  gitlabBaseUrl: String
  glNamespaces: GlApiNamespaceConnection
  hasForcedPlan: Boolean!
  id: ID!
  includedScreenshots: Int!
  inviteLink: String
  me: TeamMember
  members(after: Int = 0, first: Int = 30, levels: [TeamUserLevel!], search: String, sso: Boolean): TeamMemberConnection!
  meteredSpendLimitByPeriod: Int
  metrics(input: AccountMetricsInput!): AccountMetrics!
  name: String
  oldPaidSubscription: AccountSubscription
  periodEndDate: DateTime
  periodStartDate: DateTime
  permissions: [AccountPermission!]!
  plan: Plan
  projects(after: Int = 0, first: Int = 30): ProjectConnection!
  slackInstallation: SlackInstallation
  slug: String!
  ssoGithubAccount: GithubAccount
  stripeClientReferenceId: String!
  stripeCustomerId: String
  subscription: AccountSubscription
  subscriptionStatus: AccountSubscriptionStatus
}

enum TeamDefaultUserLevel {
  contributor
  member
}

type TeamGithubMember implements Node {
  githubAccount: GithubAccount!
  id: ID!
  teamMember: TeamMember
}

type TeamGithubMemberConnection implements Connection {
  edges: [TeamGithubMember!]!
  pageInfo: PageInfo!
}

type TeamMember implements Node {
  id: ID!
  level: TeamUserLevel!
  user: User!
}

type TeamMemberConnection implements Connection {
  edges: [TeamMember!]!
  pageInfo: PageInfo!
}

enum TeamUserLevel {
  contributor
  member
  owner
}

type Test implements Node {
  changes(after: Int!, first: Int!, period: MetricsPeriod!): TestChangesConnection!
  firstSeenDiff: ScreenshotDiff
  id: ID!
  lastSeenDiff: ScreenshotDiff
  metrics(period: MetricsPeriod): TestMetrics!
  name: String!
  status: TestStatus!
}

input TestAutomationRuleInput {
  actions: [AutomationActionInput!]!
  event: String!
  projectId: String!
}

type TestChange implements Node {
  id: ID!
  stats(period: MetricsPeriod!): TestChangeStats!
}

type TestChangeStats {
  firstSeenDiff: ScreenshotDiff!
  lastSeenDiff: ScreenshotDiff!
  totalOccurences: Int!
}

type TestChangesConnection implements Connection {
  edges: [TestChange!]!
  pageInfo: PageInfo!
}

type TestMetricData {
  changes: Int!
  consistency: Float!
  flakiness: Float!
  stability: Float!
  total: Int!
  uniqueChanges: Int!
}

type TestMetricDataPoint {
  changes: Int!
  total: Int!
  ts: Timestamp!
  uniqueChanges: Int!
}

type TestMetrics {
  all: TestMetricData!
  series: [TestMetricDataPoint!]!
}

type TestReport {
  stats: TestReportStats
  status: TestReportStatus!
}

type TestReportStats {
  duration: Int
  startTime: DateTime
}

enum TestReportStatus {
  failed
  interrupted
  passed
  timedout
}

enum TestStatus {
  ONGOING
  REMOVED
}

scalar Time

enum TimeSeriesGroupBy {
  day
  month
  week
}

scalar Timestamp

input TransferProjectInput {
  id: ID!
  name: String!
  targetAccountId: ID!
}

input UninstallSlackInput {
  accountId: ID!
}

input UnlinkGithubRepositoryInput {
  projectId: ID!
}

input UnlinkGitlabProjectInput {
  projectId: ID!
}

input UpdateAccountInput {
  blockWhenSpendLimitIsReached: Boolean
  gitlabAccessToken: String
  id: ID!
  meteredSpendLimitByPeriod: Int
  name: String
  slug: String
}

input UpdateAutomationRuleInput {
  actions: [AutomationActionInput!]!
  conditions: [AutomationConditionInput!]!
  events: [String!]!
  id: String!
  name: String!
}

input UpdateProjectInput {
  autoApprovedBranchGlob: String
  defaultBaseBranch: String
  defaultUserLevel: ProjectUserLevel
  id: ID!
  name: String
  private: Boolean
  summaryCheck: SummaryCheck
}

input UpdateProjectPrCommentInput {
  enabled: Boolean!
  projectId: ID!
}

type User implements Account & Node {
  additionalScreenshotsCost: Float!
  avatar: AccountAvatar!
  blockWhenSpendLimitIsReached: Boolean!
  consumptionRatio: Float!
  currentPeriodScreenshots: Int!
  email: String
  ghInstallations: GhApiInstallationConnection!
  githubAccount: GithubAccount
  gitlabAccessToken: String
  gitlabBaseUrl: String
  gitlabUser: GitlabUser
  glNamespaces: GlApiNamespaceConnection
  googleUser: GoogleUser
  hasForcedPlan: Boolean!
  hasSubscribedToTrial: Boolean!
  id: ID!
  includedScreenshots: Int!
  lastSubscription: AccountSubscription
  meteredSpendLimitByPeriod: Int
  metrics(input: AccountMetricsInput!): AccountMetrics!
  name: String
  oldPaidSubscription: AccountSubscription
  periodEndDate: DateTime
  periodStartDate: DateTime
  permissions: [AccountPermission!]!
  plan: Plan
  projects(after: Int = 0, first: Int = 30): ProjectConnection!
  projectsContributedOn(after: Int = 0, first: Int = 30, projectId: ID!): ProjectContributorConnection!
  slackInstallation: SlackInstallation
  slug: String!
  stripeClientReferenceId: String!
  stripeCustomerId: String
  subscription: AccountSubscription
  subscriptionStatus: AccountSubscriptionStatus
  teams: [Team!]!
}

type UserConnection implements Connection {
  edges: [User!]!
  pageInfo: PageInfo!
}

enum ValidationStatus {
  accepted
  rejected
  unknown
}