export default {
  BUILD_FETCH: 'BUILD_FETCH',
  BUILD_FETCH_TASK: 'BUILD_FETCH_TASK',

  REPOSITORY_DETAILS_FETCH: 'REPOSITORY_DETAILS_FETCH',
  REPOSITORY_DETAILS_FETCH_TASK: 'REPOSITORY_DETAILS_FETCH_TASK',

  PROFILE_FETCH: 'PROFILE_FETCH',
  PROFILE_FETCH_TASK: 'PROFILE_FETCH_TASK',

  DASHBOARD_FETCH: 'DASHBOARD_FETCH',
  DASHBOARD_FETCH_TASK: 'DASHBOARD_FETCH_TASK',
}
