export default {
  BUILD_FETCH: 'BUILD_FETCH',
  BUILD_FETCH_TASK: 'BUILD_FETCH_TASK',

  REPOSITORY_DETAILS_FETCH: 'REPOSITORY_DETAILS_FETCH',
  REPOSITORY_DETAILS_FETCH_TASK: 'REPOSITORY_DETAILS_FETCH_TASK',
}
