export type ErrorCode =
  | "GITHUB_ACCOUNT_ALREADY_ATTACHED"
  | "ARGOS_ACCOUNT_ALREADY_ATTACHED_TO_GITHUB"
  | "GITHUB_AUTH_INCORRECT_CLIENT_CREDENTIALS"
  | "GITHUB_AUTH_REDIRECT_URI_MISMATCH"
  | "GITHUB_AUTH_BAD_VERIFICATION_CODE"
  | "GITHUB_AUTH_UNVERIFIED_USER_EMAIL";
